### ISSUE TITLE
遇到emoji弹幕会出错

### ISSUE THREAD

**Issue by dtlnor** [fireattack/nicodanmaku2ass#1]
log

```
Dialogue: 2,0:01:18.91,0:01:23.91,Danmaku2ASS_d8cd,,0000,0000,0000,,{\move(683, 0, -100, 0)}はおー！
Dialogue: 2,0:01:20.79,0:01:25.79,Danmaku2ASS_d8cd,,0000,0000,0000,,{\move(683, 0, -200, 0)}はおー！！🥕�Dialogue: 2,0:01:20.79,0:01:25.79,Danmaku2ASS_d8cd,,0000,0000,0000,,{\move(683, 0, -200, 0)}はおー！！🥕�Traceback (most recent call last):
  File "danmaku2ass.py", line 398, in <module>
    main()
  File "danmaku2ass.py", line 394, in main
    Danmaku2ASS(args.file, args.output, width, height, args.protect, args.font, args.fontsize, args.alpha, args.duration_marquee, args.duration_still, args.filter, args.filter_file, args.reduce)
  File "danmaku2ass.py", line 342, in Danmaku2ASS
    ProcessComments(comments, fo, stage_width, stage_height, reserve_blank, font_face, font_size, text_opacity, duration_marquee, duration_still, filters_regex, is_reduce_comments, progress_callback)
  File "danmaku2ass.py", line 137, in ProcessComments
    WriteComment(f, i, row, width, height, bottomReserved, fontsize, duration_marquee, duration_still, styleid)
  File "danmaku2ass.py", line 249, in WriteComment
    f.write('Dialogue: 2,%(start)s,%(end)s,%(styleid)s,,0000,0000,0000,,{%(styles)s}%(text)s\n' % {'start': ConvertTimestamp(c['timeline']), 'end': ConvertTimestamp(c['timeline'] + duration), 'styles': ''.join(styles), 'text': text, 'styleid': styleid})
OSError: [WinError 87] The parameter is incorrect
Dialogue: 2,0:01:20.79,0:01:25.79,Danmaku2ASS_d8cd,,0000,0000,0000,,{\move(683, 0, -200, 0)}はおー！！🥕�Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [WinError 87] The parameter is incorrect
Dialogue: 2,0:01:20.79,0:01:25.79,Danmaku2ASS_d8cd,,0000,0000,0000,,{\move(683, 0, -200, 0)}はおー！！🥕�Dialogue: 2,0:01:20.79,0:01:25.79,Danmaku2ASS_d8cd,,0000,0000,0000,,{\move(683, 0, -200, 0)}はおー！！🥕�🥕
```

原始彈幕文件
https://gist.github.com/dtlnor/3b4b4b40fac425d4e0ac64f4c05bda1b

**Comment by fireattack** [comment]
不好意思，GitHub fork的project默认没提醒，没看到
应该是输出到stdout的问题，f786b7a65131c55bc63c76c83b06ea48d8a2596c  改成如果不提供`-o`参数直接输出到 {intput filename}.ass 文件了

我用你的文件测试可以正常工作了，你再试试？

**Comment by fireattack** [comment]
Assume it's fixed.
